name: Java CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: lấy mã nguồn code(checkout)
        uses: actions/checkout@v4

      - name: Cài đặt môi trường JDK-17
        uses: actions/setup-java@v4
        with:
          java-version : '17'
          distribution : 'temurin'
          cache : 'maven' #tự động lưu dependencies

      - name: chạy Maven
        run : mvn clean package

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-jar
          path: target/*.jar
