name: Realistic Auto Commit

on:
  schedule:
    # Chạy vào lúc 08:00 sáng mỗi ngày (giờ Việt Nam là 15:00 UTC)
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Random Commits
        run: |
          # 1. Xác định tỉ lệ muốn commit (ví dụ: 80% số ngày sẽ có commit)
          if [ $(( $RANDOM % 10 )) -gt 1 ]; then
            
            # 2. Tạo số lượng commit ngẫu nhiên từ 1 đến 5
            NUM=$((1 + $RANDOM % 5))
	    DOT=$(($NUM * 14234121343))
            echo "$DOT"
            
            for i in {1..$NUM}
            do
              echo "Cập nhật lúc: $(date +'%Y-%m-%d %H:%M:%S') - Lần: $i" >> daily_log.txt
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add daily_log.txt
              git commit -m "docs: cập nhật tài liệu hệ thống $(date +'%d/%m/%Y %H:%M')"
              
              # Nghỉ một chút giữa các commit để trông tự nhiên hơn
              sleep $((RANDOM % 10)) 
            done
            
            git push
          else
            echo "Hôm nay 'nghỉ xả hơi', không có commit nào."
          fi